apiVersion: extensions/v1
kind: Ingress
metadata:
  name: crsliotkubedev
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - crsliotkubedev.centralus.cloudapp.azure.com
    secretName: tls-prod
  rules:
  - host: crsliotkubedev.centralus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: reverse-proxy
          servicePort: 10080
        path: /(.*)